const countSelector = " > div > div.collection-list > div > p > span.now-count";

export const selector = {
	characterName: "span.profile-character-info__name",
	server: "span.profile-character-info__server",
	guild: "div.game-info > div.game-info__guild > span:nth-child(2)",
	characterClass: "div.profile-character-info > img",
	characterTitle: "div.game-info__title > span:nth-child(2)",
	level: "div.level-info__item > span:nth-child(2)",
	itemLevel: "div.level-info2__expedition > span:nth-child(2)",
	expeditionLevel: "div.level-info__expedition > span:nth-child(2)",
	duelLevel: "div.level-info__pvp > span:nth-child(2)",
	possessionLevelFirst: "div.game-info__wisdom > span:nth-child(2)",
	possessionLevelSecond: "div.game-info__wisdom > span:nth-child(3)",
	countSelector: " > div > div.collection-list > div > p > span.now-count",
	island: "#lui-tab1-1 " + countSelector,
	star: "#lui-tab1-2 " + countSelector,
	heart: "#lui-tab1-3 " + countSelector,
	picture: "#lui-tab1-4 " + countSelector,
	mokoko: "#lui-tab1-5 " + countSelector,
	expedition: "#lui-tab1-6 " + countSelector,
	ignea: "#lui-tab1-7 " + countSelector,
	leaf: "#lui-tab1-8 " + countSelector,

	combatPower: "#profile-ability > div.profile-ability-basic > ul > li:nth-child(1) > span:nth-child(2)",
	healthPoint: "#profile-ability > div.profile-ability-basic > ul > li:nth-child(2) > span:nth-child(2)",
	criticalScore: "#profile-ability > div.profile-ability-battle > ul > li:nth-child(1) > span:nth-child(2)",
	specializationScore: "#profile-ability > div.profile-ability-battle > ul > li:nth-child(2) > span:nth-child(2)",
	suppressScore: "#profile-ability > div.profile-ability-battle > ul > li:nth-child(3) > span:nth-child(2)",
	speedScore: "#profile-ability > div.profile-ability-battle > ul > li:nth-child(4) > span:nth-child(2)",
	patienceScore: "#profile-ability > div.profile-ability-battle > ul > li:nth-child(5) > span:nth-child(2)",
	skilledScore: "#profile-ability > div.profile-ability-battle > ul > li:nth-child(6) > span:nth-child(2)",
	intelligence: "#chart-states-wrap > div.states_box > span.states-01 > span > em",
	courage: "#chart-states-wrap > div.states_box > span.states-02 > span > em",
	charming: "#chart-states-wrap > div.states_box > span.states-03 > span > em",
	kindness: "#chart-states-wrap > div.states_box > span.states-04 > span > em",
};
